---
output: github_document
---

Dear fellow fighters of climate change,

I'm very interested in your [open position for a software developer with R](https://www.r-users.com/jobs/software-developer-with-r/). I would love to use my experience to help you fight climate change.

Here is how my skills match what you are looking for:

> A R Coder/Software Developer who is passionate about having a meaningful, global impact

* __I am an R software developer__. I work at the [Smithsonian Institution](https://forestgeo.si.edu) for a global network of researchers who aim to better __understand and predict forest dynamics in the face of climate__. (Unfortunately, the available funds will run out soon so I am seeking new opportunities.)

* My passion for having a meaningful, global impact is demonstrated by one chapter of my __[PhD thesis](http://bit.ly/mauro-lepore-phd-thesis)__ (Chapter 2) exploring the potential of a coral reef system to constitute a __refuge for corals from global warming__. Also by __[this paper](https://onlinelibrary.wiley.com/doi/full/10.1111/cobi.12997)__ exploring how __historical data can help us make better conservation decisions__.

> Genuine interest to improve our code/software infrastructure and related services

* In my current role, I developed __experience improving legacy code and related software infrastructure and services__. I would love to use my skills to help the 2° Investing Initiative align financial markets with climate goals. For example, I __created a [GitHub organization](https://github.com/forestgeo)__ with multiple repositories, transformed legacy code from [a collection of functions](http://ctfs.si.edu/Public/CTFSRPackage/) to __[a collection of R packages](https://forestgeo.github.io/fgeo/)__ _sensu stricto_. I also created a __[blog](https://fgeo.netlify.com)__, an internal __slack work space__, __tutorials__ (see [Tutorials tab](https://forestgeo.github.io/fgeo/)), and a __custom [CRAN-like repository](https://forestgeo.github.io/drat/)__ to manage and serve the release of  internal packages. 

> Experience in library creation including application of continuous integration services to ensure code quality

I have two years of __experience as a developer of [R libraries](https://forestgeo.github.io/fgeo/index.html#installation)__, using best practices including the application of [continuous integration](https://travis-ci.org/forestgeo). For example, for my current employer I built four main packages (a.k.a. libraries) and a meta-package that installs them all with a single R command ([fgeo](https://forestgeo.github.io/fgeo)). They are well tested (e.g. [here](https://coveralls.io/github/forestgeo/fgeo.tool), and [here](https://coveralls.io/github/forestgeo/fgeo.analyze)), and connected to a __[continuous integration service](https://travis-ci.org/forestge)__ so that every change __automatically builds, checks and deploys each packages and its associated website.__

> Strong R skills (3+ years’ experience in software development with R in a working context), proficiency with git

I am a __proficient with [Git](https://www.dropbox.com/s/yeti01v9mcj9s71/2018-11-05_git.pdf?dl=0)__; over the past year I have __[pushed to GitHub over 5500 commits](https://github.com/maurolepore)__.

My total practical experience as an R software developer is about three years. However, the first year in my current role was somewhat informal and I officially earned the title "R package developer" about two years ago. Overall, I have about __five years of experience working with R almost every day__. Beyond my paid work, I regularly [contribute to the R community](http://bit.ly/mauro-lepore-about).

> A pro-active problem-solver with strong analytical skills and a good sense for code quality

* I __solve problems pro-actively__ every day. In my current role I am the only software developer. I find solutions __independently__, often in books, blogs or by asking other R developers online (I reach excellent R developers at the private slack work space of [rOpenSci](https://ropensci.org/)).

* I developed strong __analytical skills during my PhD and postdoc__.

* I developed a good sense for __code quality via workshops__ (e.g. [Building Tidy Tools](https://blog.rstudio.com/2018/04/09/building-tidy-tools-workshop/)), and __books__ (e.g. [R packages](http://r-pkgs.had.co.nz/), [The pragmatic programmer](https://pragprog.com/book/tpp/the-pragmatic-programmer), [Code complete](https://www.amazon.com/Code-Complete-Practical-Handbook-Construction/dp/0735619670), [Refactoring](https://martinfowler.com/books/refactoring.html), etc.).

> Further technical expertise, such as web development, data visualisation, GUI development (e.g. with RShiny) as well as experience with SQL and Docker is very welcome

I have __experience building__ [__websites__ for R packages](https://forestgeo.github.io/fgeo/)), [blogs](https://fgeo.netlify.com), [__RShiny apps__](https://maurolepore.shinyapps.io/plottrait/). I also have some experience with __SQL queries__.

> Fluent English

* I am very __fluent__ in English. __Lived in English speaking countries for almost 10 years__ now. I did a PhD in Australia and now work in the US.

I look forward to meeting you soon. I would love learn more about your mission and further discuss how I can contribute to it. I am happy to negotiate the earliest possible starting date.

Best regards,  
Mauro

maurolepore@gmail.com  
[LinkedIn](https://www.linkedin.com/in/mauro-lepore/)  
[Recent contributions to the R community](http://bit.ly/mauro-lepore-about)  



---

Send your CV and cover letter in English indicating your earliest possible start date to: jobs@2degrees-investing.org


We are committed to building a diverse team and encourage applications from female and minority candidates.


https://www.r-users.com/jobs/software-developer-with-r/

A global, independent think tank on the integration of long-term and climate-related objectives and risks into financial market metrics, processes and regulation.

Since it was set up in 2012 with the mission to align financial markets with climate goals, the 2° Investing Initiative (2°ii) has become a pioneering think tank – with offices in Berlin, Paris, London and New York – on the integration of long-term risks and policy objectives into financial markets and regulatory frameworks. 2°ii developed the first scenario analysis tool linking financial portfolios to public policy objectives – specifically the 2°C climate goal – which is now applied to over $10 trillion assets under management across more than 1,000 financial institutions, as well as a number of financial supervisors. 2°ii co-designed the first climate-related financial regulation in the world (Art. 173 of the French Energy Transition Law). A core principle of its mission is to reduce the transaction costs across companies, financial institutions and policymakers, while guiding financial markets towards the long-term future.

Current research includes development of climate alignment tools for banks, market outlook reports and enhancement of existing, analytical methods as well as a sustainability-ready, open-source robo-adviser. 2°ii has a multi-stakeholder and independent governance framework designed to ensure the intellectual integrity of its work and its independence.


Interested in changing finance to fight climate change? Please send your CV and cover letter in English indicating your earliest possible start date to: jobs@2degrees-investing.org   We are committed to building a diverse team and encourage applications from female and minority candidates.


