---
title: "Mauro Lepore"
author: Mauro Lepore
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: false
---

Aside
================================================================================

Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> maurolepore@gmail.com
- <i class="fa fa-github"></i> [github.com/maurolepore](https://github.com/maurolepore)
- <i class="fa fa-phone"></i> +1 346-773-2738
- For more information, please contact me via email.



Skills {#skills}
--------------------------------------------------------------------------------

- Software developer with multiple R packages published on CRAN and GitHub.

- Highly proficient in R, RStudio, Git, GitHub, Bash, Travis CI.

- Quantitative researcher with PhD in ecology from a top-100 university.

- Teacher for undergraduate and postgraduate students, and researchers.

- Communicator with published academic papers, conference presentations, software documentation, blogs, video-tutorials.



Main
================================================================================

Mauro Lepore {#title}
--------------------------------------------------------------------------------

### Availability

I am not available for immediate hire but I am considering offers for the near future. I strongly prefer to work remotely within USA or from Houston, TX. The first three yeras of my current H1B visa expire on 2020-04-30. It can be transferred and extended for another three years. Alternatively, I am open so green card sponsorship.



Education
--------------------------------------------------------------------------------

### The University of Queensland

PhD (ecology, envitonmental sciences, and earth sciences)

Brisbane, Australia

2015

Thesis: Long term dynamics of coral reefs in the inshore Southern Great Barrier Reef.

### University of Buenos Aires

"Licenciatura" in Biological Sciences (7yrs; ~Bachelors + Masters)

Buenos Aires, Argentina

2008

Thesis: Estudio del crecimiento de la almeja amarilla _Mesodesma mactroides_


TODO: All that follows xxxxxxxxxxx


Research Experience
--------------------------------------------------------------------------------

### Graduate Research Assistant

Beijing Institute of Genomics, Chinese Academy of Sciences

Beijing, China

2011 - 2014

- Performed computational biology research towards understanding regulation of alternative splicing in human and mouse transcriptome.
- Found EGFR pathway related mutations, aimed to understand the impacts of cancer mutations on EGFR signaling pathway.

### Bioinformatican

My Health Gene Technology Co., Ltd.

Beijing, China

2015 - 2016

- Investigated how cancer cells spread to other parts of the body at the single cell level.

### Visiting Scientist

University of Alabama at Birmingham

AL, USA

2016 - 2018

- Investigated the role of mitochondria in development of cancer.
- Investigated the evolution of genome architecture and its role in important evolutionary events.
- Detected thrombotic thrombocytopenic purpura related mutations in mutiple patients' blood genome.
  

Professional Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

### Data Scientist, intern

SupStat Inc.

Beijing, China

2014

::: concise
- Taught R language to beginners. 
- Wrote Shiny app demos.
- Converted statistical tutorials from SPSS to R language.
:::

### Bioinformatician

My Health Gene Technology Co., Ltd.

Beijing, China

2015 - 2016

::: concise
- Analyzed whole-exome sequencing data. 
- Wrote analysis pipelines of ChIP-seq, single cell DNA-seq and single cell RNA-seq.
- Studied tumor metastasis and wrote research reports. 
- Also did case studies to identify the genetic defect causing rare disease.
:::


Teaching Experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

### Introduction to R Language for Beginners.

Instructor of R and Data Mining Training Courses at SupStat Inc.

Beijing, China

2014

### Computational Biology and Bioinformatics.

Teaching assistant of GBS CB2-201 courses at UAB

AL, USA

2016 - 2017


Selected Publications and Posters {data-icon=file}
--------------------------------------------------------------------------------

### Genetic and epigenetic signals are found predictive to the distribution of intra-individual divergence of alternative splicing.

Poster for 2013 International Conference of Genomics

Qingdao, China

2014

**Yu L**, Chen B, Zhang Z.

### ESCRT-0 complex modulates Rbf mutant cell survival by regulating Rhomboid endosomal trafficking and EGFR signaling.

J Cell Sci. 2016 May 15;129(10):2075-84.

N/A

2016 

Sheng Z, **Yu L**, Zhang T, Pei X, Li X, Zhang Z and Du W. 
