---
output:
  github_document:
    toc: true
    toc_depth: 5
---

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

### About

Mauro Lepore

[R-packages](https://www.rdocumentation.org/collaborators/name/Mauro%20Lepore)
[GitHub](https://github.com/maurolepore)
[R-videos](http://bit.ly/r-videos)
[LinkedIn](https://www.linkedin.com/in/mauro-lepore)
[Twitter](https://twitter.com/mauro_lepore)

I'm most experienced in software development, research and teaching. I implement software solutions to help researchers work in an efficient, transparent, and reproducible way. I often contribute as a developer or teacher to popular open software projects or communities (<https://maurolepore.github.io/>). 



### Recently published software

* [`r nrow(pkgsearch::pkg_search("maurolepore"))` packages published on CRAN](https://www.rdocumentation.org/collaborators/name/Mauro%20Lepore)



### Recently published academic papers

* O'Dea, Lepore et al. Nature Scientific Reports (2020). [Defining variation in pre-human ecosystems can guide conservation: An example from a Caribbean coral reef](https://www.nature.com/articles/s41598-020-59436-y).

* Leonard, Lepore et al. Paleoceanography and Paleoclimatology (2020). [A U‐Th Dating Approach to Understanding Past Coral Reef Dynamics and Geomorphological Constraints on Future Reef Growth Potential; Mazie Bay, Southern Great Barrier Reef](https://doi.org/10.1029/2019PA003768).

* O'Dea, Dillon et al. Conservation Biology (2017). [Look to the past for an optimistic future](https://conbio.onlinelibrary.wiley.com/doi/epdf/10.1111/cobi.12997).



### Other contributions to open software and reproducible research

* Expert for [eLife Innovation Leaders 2020](https://elifesciences.org/labs/b87d3cda/innovation-leaders-2020-meet-our-mentors-and-experts).

* Software peer-review:
    * [rOpenSci, gitignore package](https://github.com/ropensci/software-review/issues/303#issuecomment-496514351).

#### Meetups

* Weekly since October, 2019: [ds-incubator meetups](https://github.com/2DegreesInvesting/ds-incubator).
* November, 2019: Speaker for the webinar "[Ayuda para solicitudes de fusion en GitHub](https://youtu.be/PSNNbeVUxFc)" (Spanish) for [DataLatam](https://www.youtube.com/channel/UCOOcd7f7eJTDNxKLde3lfOQ).
* October, 2019: Speaker at the [meetup](https://www.meetup.com/renbaires/events/266047066/) about ["Ayuda para solicitudes de fusión en GitHub"](https://github.com/an-org/datos-de-miercoles) (Spanish), for [RenBaires](https://twitter.com/renbaires), at [Medallia Argentina](https://twitter.com/MedalliaArg).
* August, 2019: Podcast interview at [DataLatam Episodio 49](http://www.datalatam.com/49), _ONGs, ciencia de datos y dateros enfocados en hacer un mundo mejor_.
* May, 2019: Speaker for the webinar: "[Uso comun de Git](http://youtu.be/SVzyWV1Iep8 )" (Spanish) for [DataLatam](https://www.youtube.com/channel/UCOOcd7f7eJTDNxKLde3lfOQ).
* Since April 2019: Attending biweekly meetups of [instructors for The Carpentries at the Smithsonian](https://datascience.si.edu/carpentries).
* February - June 2019: Weekly [ixpantia masterclass](https://www.ixpantia.com/en/).
* October, 2018: [Speaker at meetup GitHub for projects](http://bit.ly/2pOrRXo), Library of the National Museum of Natural History, Smithsonian Institution.
* July-August, 2018: Presentations (built with and about R) at the [ForestGEO workshop in Czech Republic](http://bit.ly/event-cr18):
    * http://bit.ly/cr18-r-intro.
    * http://bit.ly/cr18-projects.
    * http://bit.ly/cr18-pipes.
    * http://bit.ly/cr18-plots.
* August, 2018: [Speaker at meetup Research with GitHub, National Museum of Natural History, Smithsonian Institution](http://bit.ly/research-with-github).
* June 27, 2018: [Teaching Assistant at meetup of RLadies-DC, led by Kelly O'Briant](https://twitter.com/kellrstats, https://www.meetup.com/rladies-dc/events/251799760/).
* June, 2018: [Led meeting, with runconf18 folks, on building R packages](https://twitter.com/mauro_lepore/status/1008136303182008320).
* March, 2017: Speaker for the presentation [Manage and share data](https://youtu.be/7exLm5gKceY) at the workshop "Digital Data in Paleontological Research", The University of California Museum of Paleontology (UCMP).

#### Teaching

I am a [Certified instructor of The Carpentries](http://bit.ly/mauro-lepore-carpentries-certificate), and contribute to [data science training at the Smithsonian Institution](https://datascience.si.edu/carpentries) and elsewhere:

* May, 2019: [Smithsonian Spring 2019 Edition](https://smithsonianworkshops.github.io/2019-05-16-castle/)
* August, 2018: [Texas A&M University-Kingsville](https://kokbent.github.io/2018-09-29-tamu-kingsville/).
* June, 2018: [National Museum of Natural History, Smithsonian Institution](https://smithsonianworkshops.github.io/2018-06-12-nmnh/).
* March, 2018: [Smithsonian Environmental Research Center, Smithsonian Institution](https://smithsonianworkshops.github.io/2018-03-07-serc/).

#### Blogs:

* January, 2018 - August, 2018: [My blog at ForestGEO](https://fgeo.netlify.com/)
* July, 2018: [Invited post at ropensci.org about work following rOpenSci's runconf18](https://ropensci.org/blog/2018/07/17/pkginspector/).
* [Activity on community.rstudio](https://community.rstudio.com/u/mauro_lepore/summary)

#### Other Contributions:

##### Books

* Contributed to the book [Advanced R by Hadley Wickham](https://es.r4ds.hadley.nz/).

* Contributed to the book [R para Ciencia de Datos by Garrett Grolemund and Hadley Wickham](https://adv-r.hadley.nz/introduction.html#intro-ack).

* Contributed to the book [Advanced R by Hadley Wickham](https://adv-r.hadley.nz/introduction.html#intro-ack).

##### Packages

* Contributed to multiple, popular R-packages (e.g.: [dplyr](https://blog.rstudio.com/2017/06/13/dplyr-0-7-0/), [usethis](https://www.tidyverse.org/articles/2019/04/usethis-1.5.0/), [styler](https://www.tidyverse.org/blog/2019/11/styler-1-2-0/), [roxygen2](https://www.tidyverse.org/blog/2019/11/roxygen2-7-0-0/), [pkgdown](https://www.tidyverse.org/blog/2019/09/pkgdown-1-4-0/)).

### Training

* January, 2019: [What they forgot to teach you about R aka Getting s*%! done in R](https://whattheyforgot.org/) - 2 days, by [Jenny Bryan](https://jennybryan.org/about/) and [Jim Hester](https://www.linkedin.com/in/jim-hester/). Austin, USA.
* September, 2018: [Writing R functions for fun and profit](https://www.meetup.com/rladies-buenos-aires/events/253987224/) - 2h, by [Jenny Bryan](https://jennybryan.org/about/). Buenos Aires, Argentina.
* September, 2018: [How to repeat yourself with purrr](http://latin-r.com/schedule/#session-3) - half day, by [Jenny Bryan](https://jennybryan.org/about/).  Buenos Aires, Argentina.
* September, 2018: [Visualización estática e interactiva de datos usando ggplot2 y plotly](http://latin-r.com/schedule/#session-1) - half day, by [Natalia da Silva](http://natydasilva.com/). Buenos Aires, Argentina.
* June, 2018: [DataCarpentry instructor training](https://i.imgur.com/f86ieG4.png). Online.
* June, 2018: [Introduction to the Smithsonian Institution High Performance Cluster (SI/HPC)](https://i.imgur.com/kObg0FC.png). Online.
* May, 2018: [Building tidy tools](https://blog.rstudio.com/2018/04/09/building-tidy-tools-workshop/) - 2 days, by [Hadley Wickham](http://hadley.nz/). San Francisco, USA.

### Meetings

* September, 2019, [eLife Innovation Sprint](https://sprint.elifesciences.org/), Cambridge, UK.
* March, 2019: [chirunconf](https://chirunconf.github.io/#team), Chicago, USA.
* January, 2019:[rstudio::conf](https://www.rstudio.com/conference/), Austin, USA.
* September, 2018: [LatinR](https://i.imgur.com/TMYMQEf.png), Buenos Aires, Argentina.
* July, 2018: [ForestGEO data analysis workshop](https://www.forestgeo.si.edu/2018-forestgeo-dynamics-workshop-czech-republic). 2 weeks. Czech Republic.
* May, 2018: [runconf18](http://unconf18.ropensci.org/#participants), Seattle, USA.

### Recent grants

#### 2019

* Full scholarship to attand [eLife Innovation Sprint](https://sprint.elifesciences.org/), Cambridge, UK.
* Diversity scholarship to attend the [chirunconf](https://chirunconf.github.io/), R Unconference in Chicago, USA (USD 300).
* [Diversity scholarship](https://blog.rstudio.com/2018/08/10/rstudio-conf-2019-diversity-scholarships/) from rstudio to attend the conference rstudio::conf 2019 (USD 3,000).

#### 2018

* Professional development scholarship from the Australian Embassy in Buenos Aires (USD 1,600):
    * Workshop [Building tidy tools](https://blog.rstudio.com/2018/04/09/building-tidy-tools-workshop/), San Francisco, USA
    * [LatinR](http://latin-r.com/) conference, Buenos Aires, Argentina.
* Academic discount from RStudio to attend the workshop [Building tidy tools](https://blog.rstudio.com/2018/04/09/building-tidy-tools-workshop/), San Francisco, USA (USD 1,200).
* Scholarship to attend [rOpenSci](https://ropensci.org/)'s [runconf18](http://unconf18.ropensci.org/#participants), Seattle, USA (~USD 1,500).
