---
output: word_document
---

mail@cynkra.com



Hi Kirill and Christoph,

I am very interested in your open position for a [Data Scientist/Engineer](https://www.cynkra.com/2019/03/21/senior-data-scientist/index.html). Just like you, I am passionate about the R ecosystem. My experience should serve your customers immediately, and I would love to learn more from you and grow along with cynkra.

Here is how my experience matches what you are looking for:

> Very good knowledge of R  
> Basic knowledge of Git

I started using R in 2013. Two years ago I became an R package developer and consultant for a network of ecologists. I use R and Git almost everyday.

> Experience in Machine Learning, Statistics, Programming, Experience with Databases, Teaching, shiny, tidyverse, etc., is a plus.

* I studied and used __statistics__ both during my first degree (biology in Argentina) and PhD (ecology in Australia). 

* I learned R __programming__ during my PhD and have been using it almost daily since 2013.

* I started using __tidyverse__ packages even before the tidyverse was formally defined. I love it, use it, teach it, and contribute to it.

* I have been __teaching__ in some way almost all my adult life. I have taught at all levels from primary school to professional researchers (e.g. via The Carpentries).

* I have used __shiny__ mostly to build dashboards.

* I have taught SQL __databases__ via The Carpentries.

* I have had little exposure to __Machine Learning__. I look forward to having a professional reason to get good at it.

> 40%-100% commitment, can be adapted throughout the year

Sounds good.

> Ability and desire to learn and improve on the job

I have a burning desire to learn and improve. I continuously read and try new things that I can apply to my work and life. (Right now, for example, I am reading about data mining, C++, and negotiation.)

> Good working knowledge of written English

* My written English is good. I have studied and worked in English speaking countries for about six years now. I also study the craft of writing and try to implement what I learn.

> Very good command of spoken English or German

My spoken English is very good. Living in English speaking countries for many years helped me to became a confident and fluent speaker. Unfortunately I don't speak German.



I attach my resume and include more information at the end. I look forward to hearing more about the present and future of cynkra, and to discussing how I could contribute to its growth. For hiring purposes, you might want to know that I am a citizen of both Argentina and Italy.

All the best,  
Mauro 

More information: 

* [LinkedIn](https://www.linkedin.com/in/mauro-lepore/)
* [Twitter](https://twitter.com/mauro_lepore)
* [More about me](https://maurolepore.github.io/)
* [tor](https://CRAN.R-project.org/package=tor): An R package on CRAN
* [fgeo](https://forestgeo.github.io/fgeo/): Main work project, gathering new and legacy code
