---
output: github_document
----


# MD anderson

The University of Texas  

The University of Texas MD Anderson Cancer Center

* Division of Internal Medicine: Golo referrals
* Therapeutics Discovery Division:
  * The Institute for Applied Cancer Science (IACS)
  * ORBIT (Oncology Research for Biologics and Immunotherapy Translation)
  * Neurodegeneration Consortium
  * TRACTION (Translational Research to Advance Therapeutics and Innovation in Oncology)
    * [Computational Biology - Institute Associate Scientist III](https://jobs.mdanderson.org/search/jobdetails/computational-biology---institute-associate-scientist-iii/e3f4ef5f-6e8b-4764-ada4-f1a69869988c?s_cid=nas&s_cid=NatureJobs)  
    
    > The candidate will integrate computational modeling with quantitative experimental data to understand complex biological systems and translate this understanding to support oncology drug development.
    
    Salary: 64,500-97,000  
    Degrees: Min BS, pref MS  
    Experience: 
      * Required: Three years of relevant research experience in lab. With preferred degree, one year of required experience.
      * Preferred: 
        * Strong foundation in both computer science concepts and molecular / cancer biology. 
        * Proficient in PERL/Python, UNIX, and statistical computing platforms (R, Matlab, etc). 
        * Experience manipulating large volume datasets and experience with high performance computing are essential. 
        * Familiar with appropriate data normalization techniques and analysis of batch effects. 
        * Previous hands-on experience working with computational and statistical tools for the analysis of biological datasets. 
        * Specifically, the applicant should have experience with machine-learning and/or data mining algorithms (ie. Clustering, classification, etc.), and experience utilizing common parametric and non-parametric statistical tests (ie. T-test, ANOVA, Wilcoxon- signed-rank test, Fisher's exact test, etc.) for data analysis. 



# Computational Biology - Institute Associate Scientist III

Dear MD Anderson HR and TRACTION team,

I am interested in your open position for a [Computational Biology - Institute Associate Scientist III](https://jobs.mdanderson.org/search/jobdetails/computational-biology---institute-associate-scientist-iii/e3f4ef5f-6e8b-4764-ada4-f1a69869988c?s_cid=nas&s_cid=NatureJobs). I have education and experience using statistics and engineering for biological research. This position seems like an excellent opportunity for me to contribute analytical and statistical support the discovery and development of new drugs.

Here is how my skills match what your are looking for:


Experience: 

> Three years of relevant research experience in lab. With preferred degree, one year of required experience.


Preferred: 

> Strong foundation in both computer science concepts and molecular / cancer biology. 

* As a biologist, I studied molecular biology deeply.
* As a researcher (doctoral and postdoctoral), I used computer science concepts to develop custom software to mine data to explore interesting patterns. I continuously train myself via  online courses, books, workshops, and conferences.
* As a software developer (current job) I use computer science concepts to engineer efficient and maintainable software solutions for researchers I support.

> Proficient in PERL/Python, UNIX, and statistical computing platforms (R, Matlab, etc).

* As a certified instructor of The Carpentries, I teach and help teach Python for data analysis. 

* As a software developer, I use R and a UNIX-like application (Git bash) at the expert level for software development and version control.

* As a researcher and data science consultant, I use R at the expert level to extract, transform, model, and visualize data, and to communicate insights. I do this almost daily, at the expert level.

> Experience manipulating large volume datasets and experience with high performance computing are essential. 

* I fluently use tools and strategies to manipulate large datasets.

* I have been trained and certified to operate the high-performance cluster of the Smithsonian Institution (certificate at http://bit.ly/2IK0N79).

> Familiar with appropriate data normalization techniques and analysis of batch effects. 

* As a scientist working on a statistics-intensive field (ecology) I have used appropriate normalization techniques multiple times.

> Previous hands-on experience working with computational and statistical tools for the analysis of biological datasets. 

* As a researcher, software developer, and data science consultant, I have many years of experience working with computational and statistical tools for the analysis of biological datasets. 

> Specifically, the applicant should have experience with machine-learning and/or data mining algorithms (ie. Clustering, classification, etc.), and experience utilizing common parametric and non-parametric statistical tests (ie. T-test, ANOVA, Wilcoxon- signed-rank test, Fisher's exact test, etc.) for data analysis. 

* In my research I have explored patterns and variability in biological samples using, among other methods, clustering, principal components analysis, and multiple parametric and non-parametric tests. 

I look forward to hearing from you soon.

Best regards,
Mauro Lepore, PhD

maurolepore@gmail.com
