### What they forgot to teach you about R

RStudio, Inc.  
2019-01  
Certificate <https://i.imgur.com/AZhx1By.jpg>  

### Introduction to Git for Data Science

DataCamp  
2018-11  
Certificate <http://bit.ly/2OkqfQD>  

### Python for R Users

DataCamp  
2018-11  
Certificate <http://bit.ly/2U50iJZ>  

### Introduction to Shell for Data Science

DataCamp  
2018-10  
Certificate <http://bit.ly/2YkytNk>  

### Writing Efficient R Code

DataCamp  
2018-10  
Certificate <http://bit.ly/2Fm1W0w>  

### Introduction to the Smithsonian Institution High Performance Cluster

Smithsonian Institution  
2018-06  
Certificate <https://i.imgur.com/kDAe7cR.png>  

### Building tidy tools

RStudio, Inc.
2018-05  
Certificate <https://i.imgur.com/C6QSUWP.jpg>  

### Statistical computing using R

Smithsonian Tropical Research Institute, Panama City, Panama  
2016-07  

### Software carpentry bootcamp for ecologists and evolutionary biologists

The Centre for Ecosystem Science, University of New South Wales, Sydney, Australia  
2014-02  

### Advanced R

Centre for Applications in Natural Resource Mathematics, The University of Queensland, Australia  
2014-11  

### Introduction to R

Centre for Applications in Natural Resource Mathematics, Australia  
2013-11  

### Other data science courses

Coursera  
2013 - 2014  

* Computing for data analysis
* Statistics one
* Data analysis

Specialization in data science: 

* The Data Scientist’s Toolbox
* R Programming
* Getting and Cleaning Data
* Exploratory Data Analysis
* Reproducible Research
* Statistical Inference
* Regression Models
* Practical Machine Learning
* Developing Data Products
