---
output: pdf_document
---

__Mauro Lepore__

```{r, child="contact.Rmd"}
```

---

__Tonya Filz__  
Manager - Customer Success Team, RStudio  

Dear Tonya Filz,

Your open position for a [Customer Success Representative](https://hire.withgoogle.com/public/jobs/rstudiocom/view/P_AAAAAACAAJZPJ1EPP3oDOq) seems like an excellent opportunity for me to contribute to the growth and profit of RStudio. RStudio products have helped in my own success, and I would love to multiply the effect by helping your customers be also wildly successful.

Here is what you are looking for matches my skills and expertise:

* I learned to build trusted relationships and a deep understanding of my customers' needs during the many years I worked as a wedding photographer. And I truly enjoy sharing insights and resources, particularly about RStudio products. I do it frequently in my job, as an instructor of The Carpentries, and as a member of the R community. 

* I have several years of experience selling photography, two years of experience as an R  developer and consultant in my current job, and many accumulated year of experience as a trainer and teacher for learners from primary school to professional researchers. Also I have plenty experience as a problem-solver, first as a photographer, then as a researcher, and now as a package developer.

* I am so keenly interested in statistics and data science that I hold a PhD in ecology, and now work as an R package developer and consultant, which also demonstrates that my background in R programming is strong.

* I fully embrace the practice of continuous learning. I am most curious about data science, software engineering and human behavior. I read about one of these topics almost everyday.

* I learned a lot about being humble by going way beyond my comfort zone and feeling the impostor syndrome. This more clearly happened by living in different countries and by doing a PhD. I believe in continuous improvement, so I will always consider myself a "work in progress". I love team work and I look forward to collaborating with others regularly. I have greatly enjoyed rOpenSci's runconf 2018 and chirunconf 2019.

* I am very effective working in a distributed team. Although I now work from an office, the people I interact with are almost always elsewhere. In fact, the last year of my PhD I worked from home and I accomplished the deepest, most productive work of my life. Yet I made time to read, exercise, eat healthy, and enjoy everyday life with my partner.

Please find my resume attached. I would appreciate the opportunity to meet with you and further discuss how I can help your team meet its goals.

Sincerely,  
Mauro Lepore  
