### The University of Queensland, Australia

PhD, Ecology, Environmental Sciences, Geochemistry  
2011-2015  
School of Biological Sciences, ARC Center of Excellence for Coral Reef Studies  

My PhD research looked  at historical changes over the past 8,000 years in coral reefs in the southern Great Barrier Reef (Australia). 

Thesis: "Long term dynamics of coral reefs in the inshore southern Great Barrier Reef".

I examined three issues:

1. The potential of a reef system  to constitute a refuge  for coral reefs from global warming.
2. The accretion rate of the  reef flat and reef  slope environment through time.
3. Changes in coral community structure through time, and the mechanisms of  community assembly.

### Universidad de Buenos Aires, Argentina

Licentiate degree, Biological Sciences, Marine Ecology  
1999-2008  
Faculty of Natural Sciences  

Thesis: "Estudio del crecimiento de la almeja amarilla Argentina Mesodesma mactroides por marcaje fluorescente in situ y comparación con el método de análisis de distribuciones de frecuencias de tallas".

I compared a novel and traditional method to study the growth rate of a clam.

