### Teaching university students

Smithsonian Tropical Research Institute  
2016-12  
Smithsonian Tropical Research Institute, Bocas del Toro Research Station, Panama  

Teaching assistant for university students from Texas A&M University (GEOS405) during a five-days long field-based research. Responsible for delivering lectures, mentoring research projects, boating and snorkeling safety, logistics in English and Spanish.

### Teaching university students

The University of Queensland  
2012-04 - 2014-11  

* St Lucia, Brisbane, Australia
* Moreton Bay Research Station, North Stradbroke Island, Australia
* Heron Island Research Station, Heron Island, Australia

Teaching assistant for university students, including classroom-based courses (MARS2014), and field-based research for resident students of The University of Queensland (MARS2005), and for international students from Stanford University and the University of California. Responsible for delivering lectures, mentoring research projects, marking assignments, boating and snorkeling safety, logistics.

### Teaching high school students

The University of Queensland  
2011-04 - 2015-06  

* Moreton Bay Research Station, North Stradbroke Island, Australia
* St Lucia, Brisbane, Australia

Lecturer and demonstrator during science camps for high school students doing lab- and field-based research. Also responsible for liaising with school teachers and training less experienced tutors.

### Outreach

2003-07 - 2003-12 and 2004-04 - 2004-08  
Museo Argentino de Ciencias Naturales, Argentina  
Parque Centenario, Buenos Aires, Argentina  

Responsible for explaining the exhibition at the national museum of natural history in Buenos Aires, Argentina, to engage the general public, from kids to adults, and primary school groups.
