# PEER REVIEWED ARTICLES

Herrmann M, Alfaya JEF, __Lepore ML__, Penchaszadeh PE, Arntz WE (2011) Population structure, growth and production of the yellow clam Mesodesma mactroides (Bivalvia: Mesodesmatidae) from a high-energy, temperate beach in northern Argentina. Helgoland Marine Research, 65, 285-297.

Herrmann M, Alfaya JEF, __Lepore ML__, Penchaszadeh PE, Laudien J (2009a) Reproductive cycle and gonad development of the Northern Argentinean Mesodesma mactroides (Bivalvia: Mesodesmatidae). Helgoland Marine Research, 63, 207-218.

Herrmann M, __Lepore ML__, Laudien J, Arntz WE, Penchaszadeh PE (2009b) Growth estimations of the Argentinean wedge clam Donax hanleyanus: A comparison between length-frequency distribution and size-increment analysis. Journal of Experimental Marine Biology and Ecology, 379, 8-15.

__Lepore ML__, Penchaszadeh PE, Alfaya JEF, Herrmann M (2009) Application of calcein for estimating growth of the yellow clam Mesodesma mactroides Reeve, 1854. Revista de Biología Marina y Oceanografía, 44, 767-774.
