# PROFESSIONAL APPOINTMENTS

## 2017-04 to 2017-06. Postdoctoral Fellow.

Smithsonian Tropical Research Institute (STRI), Roosevelt Ave. Tupper Building – 401, Panama City (9100), Panama.

Project #3976: Quantifying Ecological Changes in Reef-Building Corals from Bocas del Toro since 7,000 years ago (STRI Host/Advisor: Aaron O'Dea). 
Computational tools and techniques are crucial in natural-sciences research (e.g. these two papers published in nature in 2017: (1) neuroscience https://goo.gl/QgvAEx; (2) ecology & evolution https://goo.gl/L0z4Fg). In this project, I have been exercising not only my ecological skills but also my IT skills.

For over one year, I have heavily used (and expanded) my skills in software development in R and in data management with Git and GitHub. Those tools I have used to develop multiple products of my research, including analyses, plots, data sets, and reports of multiple types. (Reports succinctly integrate all other products, and communicate ideas hiding implementation details that may bore or confuse the viewer.) A few examples include:
  
  * Presentation for research meeting (built using R Markdown Presentations; used GitHub to host data (privately) and for software version-control; the data-science workflow was managed with tidyverse packages):
  
  * February, 2017. Lepore ML and O’Dea A. Pristine reefs wanted dead or alive. STRI fellows’ symposium, Tupper, Smithsonian Tropical Research Institute, Panama (https://goo.gl/i3lHe8).

* Presentations to motivate learning and using computational tools and techniques for research (built using R Markdown Presentations).

* March 28, 2017. Lepore ML. Manage and share data with GitHub and R packages (https://goo.gl/2afS7R). Invited speaker at the workshop on Digital Data in Paleontological Research, UC Berkeley, USA https://goo.gl/h67f4v).

* November 09, 2016. Lepore ML. Why and how to use git with R Studio (https://goo.gl/2WMfqL). Training for students. Naos, Smithsonian Tropical Research Institute, Panama.

* August 28, 2016. Lepore ML, Kelly A. Managing and Sharing Data (https://goo.gl/LKF93D). Lab seminar. Naos, Smithsonian Tropical Research Institute, Panama.

* GitHub repository of a guide to identify corals from the Caribbean (https://github.com/maurolepore/ccsig) and its corresponding images gallery, served by GitHub (https://maurolepore.github.io/ccsig/).

* Website to host the development version of my research and to communicate internally with my students and STRI advisor (rpubs.com/maurolepore/coral; built using R Markdown flexadashboards; used GitHub to host data (privately) and for software version-control; the data-science workflow was managed with tidyverse packages).

## 2016-02 to 2016-04. Short Term Fellow (research).

Smithsonian Tropical Research Institute (STRI), Roosevelt Ave. Tupper Building – 401, Panama City (9100), Panama.

## 2016-12. Tutor from STRI for GEOS 405, Texas A&M University

Five days trip to Bocas del Toro, Panama.

Teaching assistant including lecturing and advising students in the development of their independent research projects. Also responsible for snorkeling safety and for translating guided tours from Spanish to English.

## 2011-04 to 2015-06 Tutor for Science Camps.

Moreton Bay Research Station (MBRS), The University of Queensland.

Lecturer and demonstrator for high school students (groups > 50). Responsible for liaising with school teachers and coordinating less experienced tutors in running lab- and field based activities.

## 2014-11. Tutor for Stanford University students.

One week trip to MBRS.

International Programs, The University of Queensland.

Teaching assistant including marking. Also responsible for boating and snorkeling safety, field and lab gear and driving groups of students (> 10).

## 2014-06. Tutor for UQ Experience Science

Two days at The University of Queensland.

Teaching assistant. Responsible for supervising lab activities of high school students during promotional visits to the University of Queensland.

## 2014-04. Tutor for UQ MARS2005

Two weeks trip to Heron Island Research Station (HIRS), The University of Queensland.

Teaching assistant including mentoring groups of students (> 5) in the development of independent projects. Responsible lab- and field based activities.

## 2014-03. Tutor for UQ MARS2005

Two 3-days trip to MBRS, The University of Queensland.

Teaching assistant including marking exams and mentoring groups of students (> 5) in the development of independent research projects. Responsible lab- and field gear and activities, and for boating and snorkeling safety.

## 2014-03. Tutor for UQ MARS2014

One semester at  The University of Queensland.

Teaching assistant. Responsible for delivering introductory lectures during field activities and for mentoring groups of students in the development of independent research projects on campus.

## 2013-09. Tutor for Stanford University students.

One week trip to MBRS,  International Programs, The University of Queensland.

Teaching assistant. Responsible for boating and snorkeling safety, field and lab gear and driving groups of students (> 10).

## 2012-09. Tutor for students from the University of California.

Ten days trip to MBRS, International Programs, The University of Queensland.

Teaching assistant. Responsible mentoring groups of students (> 5) in the development of independent research projects.

## 2012-04. Tutor for UQ MARS2014.

One semester at The University of Queensland.

Teaching assistant including marking students presentations, mentoring their independent research projects and for supervising field activities.

## 2004-04 to 2004-08, and 2003-07 to 2003-12. Speaker in guided tours, Museo Argentino de Ciencias Naturales, Argentina.

Responsible for explaining the exhibition at the national museum of natural history in Buenos Aires, Argentina, to engage the general public, from kids to adults, and primary school groups.
