### fgeo.analyze: Analyze ForestGEO Data

2019-05 - present  
URL <https://CRAN.R-project.org/package=fgeo.analyze>  

The goal of fgeo.analyze is to implement analyses of plot species distributions, topography, demography, and biomass. It also includes a torus translation test to determine habitat associations of tree species as described by Zuleta et al. (2018) <doi:10.1007/s11104-018-3878-0>. To learn more about ForestGEO visit <http://www.forestgeo.si.edu/>.

### fgeo.tool: Import and Manipulate ForestGEO Data

2019-05 - present  
URL <https://CRAN.R-project.org/package=fgeo.tool>  

The goal of fgeo.tool is to help you to easily import, filter, and modify ForestGEO data.

### fgeo.x: Access Small ForestGEO Datasets For Examples

2019-05 - present  
URL <https://CRAN.R-project.org/package=fgeo.x>  

The goal of fgeo.x is to help you access small example datasets from Luquillo, a ForestGEO site in Puerto Rico (<https://forestgeo.si.edu/sites/north-america/luquillo>).

### tor: Import Multiple Files From a Single Directory at Once

2019-01 - present  
URL <https://CRAN.R-project.org/package=tor>  

The goal of tor (to-R) is to help you to import multiple files from a single directory at once, and to do so as quickly, flexibly, and simply as possible.

### fgeo: Analyze Forest Diversity and Dynamics

2017-03 - present  
URL <https://forestgeo.github.io/fgeo/>  

'fgeo' is a collection of R packages to analyze forest diversity and dynamics. It includes packages to manipulate and plot ForestGEO data, and to do common analyses including abundance, demography, and species-habitats associations.
