I developed and used my skills in data science both during my doctoral and post-doctoral research. I received intensive training in the R programming language and statistical environment. This training included 15 courses (see section Skills in Data Science in my CV; copied below).

Using my R skills, I have managed and analyzed all data during my PhD (2015, as cited in methods section of my PhD thesis http://espace.library.uq.edu.au/view/UQ:371899) and during the postdoctoral research at the Smithsonian Tropical Research Institute, Panama (2016-2017, https://odealab.com/, (http://rpubs.com/maurolepore/coral).

## Summary

- Software developer with multiple R packages published on CRAN and GitHub.

- Highly proficient in R, RStudio, Git, GitHub, Bash, Travis CI.

- Quantitative researcher with PhD in ecology from a top-100 university.

- Teacher for undergraduate and postgraduate students, and researchers.

- Communicator with published academic papers, conference presentations, software documentation, blogs, video-tutorials.

## Data analysis

I am proficient in tools for data analysis. For example:

* readr, to import raw data (readr.tidyverse.org).
* tidyr, to create tidy data (tidyr.tidyverse.org).
* dplyr, to manipulate data (dplyr.tidyverse.org ).
* ggplot2, to visualize data (ggplot2.tidyverse.org).
* lmer4, to model data (github.com/lme4/lme4) and modelr, to pipe-line multiple model. (github.com/tidyverse/modelr).
* knitr and friends to communicate results via reproducible reports (yihui.name/knitr).

## Software engineering

I am proficient in tools for software development. For example:

* devtools, to build and update R packages (r-pkgs.had.co.nz).
* GitHub to maintain and expand R packages, enabling software version-control and remote collaboration with co-workers .
* roxygen2, to document help pages of functions, data and packages (https://goo.gl/AmqVj0).
* profvis, to optimize code for speed (rstudio.github.io/profvis).
* A modern style guide to write easy-to-read code (style.tidyverse.org).
* dplyr, to interact with remote databases directly from R (github.com/tidyverse/dbplyr).
* rmarkdown, to produce documents of many types, including:
    * static reports in .pdf, .docx and .html format (rmarkdown.rstudio.com).
    * books, papers and other technical documents (bookdown.org/yihui/bookdown).
    * websites (https://goo.gl/pqm8F1; and for R packages hadley.github.io/pkgdown).
    * slideshows (https://goo.gl/c5sn7G).
* Shiny, to develop interactive web applications (shiny.rstudio.com).
