# VOLUNTEERS SUPERVISED

In the lab: Sarah Whiteley, Ian Butler, Marine Couraudon-Réale, Monalisa Duarte de Olivera, Elisa Fernandez-Fernandez, Peita Houlihan, Alex Nelson, Cedric Pellegrini, Omer Polak

In the field: Ian Butler, Bruno Carturan, Tara Clark, Marine Couraudon-Réale, Matthew Kosnik, Nicole Leonard, Hannah Markham, Robert Mason, Omer Polak, Martina Prazeres, Paola Rachello-Dolmen, Ruth Reef and Alberto Rodriguez

MAJOR FIELD EXPEDITIONS

2016. Underwater collection (SCUBA) of alive fish using nets from coral reefs from islands in the Pacific Panama.

2016. Underwater collection (SCUBA) of bulk samples from modern coral reefs and geologic collection of bulk samples from mid-Holocene reefs, from multiple locations in Dominican Republic.

2013. Reef matrix coring and coral death assemblage collection in Hervey Bay, south of the Great Barrier Reef (GBR), Australia. Live aboard.

2013. Reef matrix coring, coral drilling, coral death assemblage collection, air lifting for molluscs collection and benthic surveys in the Keppel Islands, southern GBR, Australia. Live aboard, 2 weeks. Lead Scientist, dive coordinator.

2012. Reef matrix coring, coral drilling, coral death assemblage collection, benthic surveys and sea level surveys in the Franklands Islands, northern GBR, Australia. Live aboard, 3 weeks.

2012. Reef matrix coring and coral death assemblage collection in Hervey Bay, south of the Great Barrier Reefs Australia.

2012. Foraminifers collection at Heron Island, GBR, Australia.

2012. Reef matrix coring, coral drilling, coral death assemblage collection and benthic surveys in the Keppel Islands, southern Great Barrier Reef (GBR), Australia (2 weeks). Lead Scientist, dive coordinator.
