---
title: "Prototype interviews"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### 2019-03, Jeff Allen

If it’s not too late, What's the best way to 'hear' your advice?

I value your experience-mix in software engineering/biology/medicine, particularly in Texas and remote. I also value your experience hiring, learning 'on the job', and supporting diversity.

#### Questions

Hi Jeff, 

Thanks a lot for offering career advice. Here are some questions. I value your time so feel to ignore them if you are busy. I first give you some background for you to understand where my questions come from.

BACKGROUND

I'm an ecologist turned software engineer about two years ago. I now work for a network of ecologists implement software solutions. Mainly, I build and maintain R packages, and support research groups in all things R/Git/GitHub. 

I'm based in Washington DC but I'd love to move to Houston TX (my partner and only close friend live there). In Houston, the medicine industry is large so I'm trying to better understand if/how I could fit.

QUESTIONS

Considering your vast experience implementing software solutions for research in biology/medicine, What would be the most valuable skills lacking in someone doing a similar job but with a formal background in biology instead of computer sciences? (i.e. what should I learn to be most marketable?)

Considering your vast experience in Texas, What industries/groups/people might need someone working from Houston (or remote) implementing software solutions in R, or technologies that an R expert could learn on the job?

Considering your experience hiring, How do you solve the paradox by which people learn the most 'on the job' but job descriptions often request specific skills (e.g. technologies) that are rare and discourage potentially great applicants?

Considering your experience working with diverse people, How could a person working on a visa (e.g. H1B visa associated to a specific job) negotiate better work conditions (e.g. work remotely) with a difficult manager without putting at risk the job and life around the job?

#### Answer

> I'm far from an expert in Visas, but my experience is that with academic institutions, it tends to be less of an issue than with industry positions. With your background in biology that might be a nice fit.

Thanks for reminding me about the divide between academic vs. industry when it comes to visas. That helps prioritize my search.

> I'm no expert on Houston, but I know MD Anderson does all sorts of interesting bioinformatics work.

Nice to hear about MD Aderson. My good friend (MD) from Houston mentioned it too and knows some people I could learn more from.

> Job descriptions will unfortunately require a lot of arbitrary experience. If it's a position that you're really excited about that requires skills you don't have, I'd encourage you to just spend a few hours poking with it. You don't have to overstate your experience in the interview, but you'd at least have your head around what the thing is and be able to say with confidence something to the effect of: 

> "I've spent a bit of time playing with that tool in my free time. I haven't had a chance to work with it professionally yet, but based on what I've seen so far I don't have any hesitation saying that I'd quickly be able to get ramped up."

> That shows initiative and it addresses the most worrying concern an interviewer is going to have: 

> is this person going to be able to learn the tools we need in order for them to be productive?

> I'd definitely encourage you to be honest about what level of experience you have in the interviews, though. 

> If I found that a candidate claimed to "know Perl" but I later found out that he'd only played with it one weekend, I'd be really skeptical about all the other things that they claim to "know."

Your perspective about job descriptions is gold to me. It's useful to know what's in the head of those who hire. 

> I'm not sure if there is an R meetup in Houston, but I'd guess there is. Not sure if they'd allow you to post remotely or if you'd be able to coordinate a trip to visit around an upcoming meeting, if one does exist. That might be a nice way to get in touch with other companies in the region doing work with R. I imagine there's plenty of oil and gas use cases for R there, too, though I don't know any specifics unfortunately.

I go to Houston once a month (to keep my relationship alive) and, as you say, I would love to meet R folks there. I did some research about meetups in Houston and very few things came up. I'm surprised given that Hadley Wickham lives there. The phyton crowd seems more organized and I may contact them.

> The most valuable skils to pursue really depend on what you want to do. In either industry or Academia, I think you'll be best off if you can develop yourself as a "T-Shaped" engineer (https://medium.com/@jchyip/why-t-shaped-people-e8706198e437 …). Pick a couple of areas where you can go deep, then just establish as much passing familiarity as you can with different languages, tools, and techniques. You won't be able to be an expert in everything, but it's great to have an applicant that can speak intelligently about a variety of topics.

Thanks for sharing the post about "T-Shaped" engineers. I had read it via one of your job posts and I think it is a great approach to develop one's skills. I'll totally re-read it and embrace it (I love and use lots of similarly pragmatic approaches to working and living life.)

> In terms of academia vs industry, you'll just have to figure out what you want. I think there's a stable career path in academia where you can really solidify yourself as a critical piece of a group as a strong technical contributor. That being said, you'll also rise to the top pretty quickly and find that you don't have a lot of other technical mentorship available. In my experience, getting into a group where I got to work with really strong senior developers has accelerated my learning/growth. But Academia is also a lot of fun and gives you a lot of variety; there's no right answer.

> ... in academia ... you'll also rise to the top pretty quickly and find that you don't have a lot of other technical mentorship available.

That's so 'on the spot'. Are you reading my mind? That's precisely why I'm not afraid of working remotely. Even when I go to an office, I talk to noone and receive feedback/mentorship from noone. Instead I prefer to be at home but interacting with and learning from senior developers. I just need to get rise to the level where they want me around :-)

> Unfortunately, negotiating for particular perks is really going to depend on the company/manager. Some places would be totally open to remote work, others would be offended by the request. I'd just look around at what others in the organization are doing and see if there's existing precedent for your requests. In terms of working remotely, I'd tread carefully. If the company isn't setup to be supportive of remote employees, you'll probably find that your career is stifled and that it will be an isolating edxperience. I'd be careful about trying to work remotely if everybody else I was working with was colocated. It really works best when many of the folks are in the same boat.

> Hope that's helpful!
> Jeff

Indeed, this is extreemely helpful. Thanks a lot Jeff!


### 2019-03, Jim Hester

Would you be open to chat for a few minutes about career path?

Your profile suggests you transitioned from analysis to engineering. I'm moving in that direction, except I'm far behind and afraid to loose touch with the analysis bit.

I'm curious about how you picked up so much technical skill. And I would love to know what career directions you see that I may be missing — considering I come from ecology and am skilled almost exclusively in R and associated tooling and super keen to expand.

### 2019-03, David Smith

Yesterday I read a post about the upcoming RStudio Instructor Training, which reminded me chatting with you at satRdays-DC about the R certification initiative. There seems to be some overlap, isn't it?

I'm starting to think about my next career challenge. If your role as mentor goes a little beyond technical aspects during the unconf, I'd love to ask you for 10' of your time to try learn how someone with your experience sees the career landscape for someone like me.

