---
output: pdf_document
---
### The Lead Instructor, Data Science

http://bit.ly/2GBxktJ

Houston, TX United States of America  

Flatiron School is seeking a Lead Instructor for Data Science for our Houston, TX campus. We are looking for people that LOVE TEACHING. We make it a mission to seek out teachers who can infect, infuse and inspire with passion, wisdom, positivity, and humor.
 

The Lead Instructor, Data Science will:

Make No Little Plans

Build for scale by planning, writing, and delivering lectures in accordance with the progress and pace of the class.
Pilot our experimental efforts in curriculum and pedagogical style pursuing our collective unending quest to provide the best experience and most positive outcomes.
Develop and lead student project sprints throughout the semester.
Radiate Positivity

Create a safe and collaborative environment where students understand that helping their peers betters their own experience.
Find what to love. Leverage passion as a force for motivation by sharing what you are passionate about with your students and working those topics into lesson plans as appropriate.
 

Be Scrappy

Embrace change and thrive in ambiguity by helping students and staff with real time efforts, like debugging a student’s project or assignment, while devoting time and effort to developing the macro learning plan.
Move quickly by prepare your own lectures but anticipating last minutes changes based on the class' progress and learning goals.
Pursue Mastery

Use feedback from students gathered via class surveys to greatly exceed the minimum bar.
Integrate feedback from team members on progress of class to set pacing and determine tactical interventions.
Work Together

Provide feedback to team members by conducting weekly 1 on 1s and over-communicating on a daily basis.
Empower others to succeed by conducting interviews for instructors and students for future cohorts.
Qualifications for Lead Instructor, Data Science:

Strong knowledge in Data Science, Data Analytics, R, Python, etc.
Strong knowledge in Statistics, Mathematics and Machine Learning
2+ years of professional experience as a data scientist
Prior experience teaching code to a class of students
Able to work cross-functionally with a variety of people from curriculum writers to engineers and designers


## Interviewer

Cynthia Minakawa  
Recruiter at Flatiron School x WeWork  
https://www.linkedin.com/in/cynthia-minakawa-4714946/  

* Recruiting since 2015
* Lives in NYC
* Speaks spanish
* Interested in 
  * Chile development
  * Teaching
  * Asian studies

  * Spanish (Houston?)

H1B visa?

I met Josh Daniell, campus director in DC
The Carpentries
Greg Wilson's workshop


