---
title: "My most recent work"
description: |
  My work in 2020.
date: 12-24-2020
author:
  - name: Mauro Lepore
    url: https://github.com/maurolepore
base_url: https://maurolepore.github.io/
output: 
  distill::distill_article:
    toc: true
    toc_depth: 3
    self_contained: true
categories:
  - about-me
preview: preview.jpg
twitter:
  site: "@mauro_lepore"
  creator: "@mauro_lepore"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  collapse = TRUE,
  comment = "#>"
)
```

I build software and help people understand their data. Here my work most recent work.

[Twitter](https://twitter.com/mauro_lepore), [GitHub](https://github.com/maurolepore), [LinkedIn](https://www.linkedin.com/in/mauro-lepore), [YouTube](http://bit.ly/r-videos).

## Contributions

* [R-packages](https://www.rdocumentation.org/collaborators/name/Mauro%20Lepore)
* [Associate editor for rOpenSci](https://github.com/ropensci/software-review#associate-editors).
* [Keynote speaker for ConnectaR
2021](https://conectar2021.github.io/ConectaR2021/agenda/).
* [Mentor for Chicago R Collaborative](https://chircollab.github.io/#team).
* [Expert for eLife Innovation Leaders
2020](https://elifesciences.org/labs/b87d3cda/innovation-leaders-2020-meet-our-mentors-and-experts).
* Popular books: [R for Data Science (Garrett Grolemund and Hadley
Wickham)](https://adv-r.hadley.nz/introduction.html#intro-ack), [Advanced R
(Hadley Wickham)](https://adv-r.hadley.nz/introduction.html#intro-ack).
* Popular R packages: [usethis
2.0.0](https://www.tidyverse.org/blog/2020/12/usethis-2-0-0/#acknowledgements),
[tidyr
1.1.0](https://www.tidyverse.org/blog/2020/05/tidyr-1.1.0/#acknowledgements),
[usethis
1.6.0](https://www.tidyverse.org/blog/2020/04/usethis-1-6-0/#thank-you).

## Teaching

* Host of [Data science incubator
meetups](https://www.youtube.com/playlist?list=PLvgdJdJDL-APbB315sB3Lv_2VP2g0ioFO).
* Host of [Tidy data science (2-day
workshop)](https://github.com/2DegreesInvesting/tidy-ds#tidy-ds).

## Blogs

* Host of [Data science at 2DII](https://2degreesinvesting.github.io).
* Guest of [MetaDocencia](https://metadocencia.netlify.app/en/): [Teaching online,
smoothly](https://metadocencia.netlify.app/en/post/experiences_mauro/).

## Papers

* O'Dea, Lepore et al. Nature Scientific Reports (2020). [Defining variation in
pre-human ecosystems can guide conservation: An example from a Caribbean coral
reef](https://www.nature.com/articles/s41598-020-59436-y) (see also news
releases
[here](https://www.si.edu/newsdesk/releases/plenty-gloom-dash-hope-fossils-help-identify-lone-bright-spot-reef-similar-state),
[here](https://stri.si.edu/story/bright-spot), and
[here](https://www.eurekalert.org/pub_releases/2020-02/stri-fhi022020.php)).
* Leonard, Lepore et al. Quaternary Science Reviews (2020). [Re-evaluating
mid-Holocene reef "turn-off" on the inshore Southern Great Barrier
Reef](https://doi.org/10.1016/j.quascirev.2020.106518).
* Leonard, Lepore et al. Paleoceanography and Paleoclimatology (2020). [A U‐Th
Dating Approach to Understanding Past Coral Reef Dynamics and Geomorphological
Constraints on Future Reef Growth Potential; Mazie Bay, Southern Great Barrier
Reef](https://doi.org/10.1029/2019PA003768).
* O'Dea, Dillon et al. Conservation Biology (2017). [Look to the past for an
optimistic
future](https://conbio.onlinelibrary.wiley.com/doi/epdf/10.1111/cobi.12997).

